//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LOPHOC
    {
        public string MALOP { get; set; }
        public string MAGV { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
