//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIANGVIEN()
        {
            this.TT_LUONGGV = new HashSet<TT_LUONGGV>();
            this.CT_LOPHOC = new HashSet<CT_LOPHOC>();
        }
    
        public string MAGV { get; set; }
        public string TENGV { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string TRINHDO { get; set; }
        public string BANGCAP { get; set; }
        public Nullable<System.DateTime> NGAYVL { get; set; }
        public Nullable<double> HESO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_LUONGGV> TT_LUONGGV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_LOPHOC> CT_LOPHOC { get; set; }
    }
}
