//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<double> HESOLUONG { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public Nullable<short> PHANQUYEN { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual PHANQUYEN PHANQUYEN1 { get; set; }
    }
}
