//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKB
    {
        public string MALOP { get; set; }
        public int MAPHONG { get; set; }
        public string MALH { get; set; }
    
        public virtual LICHHOC LICHHOC { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual PHONGHOC PHONGHOC { get; set; }
    }
}
