//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_LUONGGV
    {
        public string MATT { get; set; }
        public string MAGV { get; set; }
        public Nullable<System.DateTime> NGAYNHAN { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    
        public virtual GIANGVIEN GIANGVIEN { get; set; }
    }
}
